<?php

?>
<ul class="breadcrumb">
    <li class="active">Veuillez lire les étapes suivantes pour participer aux lotteries</li>
</ul>

<div class="row">

    <div class="col-md-4">

        <div class="panel panel-default">
            <div class="panel-heading"># STEP 1</div>
            <div class="panel-body">
                <i class="fa fa-quote-left fa-3x fa-pull-left fa-border"></i>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sodales urna tortor, in sollicitudin odio finibus et. Aenean nec nisl ultricies, condimentum tortor at, consectetur mauris. Vestibulum sit amet eros dui. Aenean maximus lacus id metus aliquam condimentum non non quam. Vivamus euismod eget nunc quis ultricies. Donec rutrum eget nisi nec sagittis. Praesent congue odio a erat consectetur, et mattis urna imperdiet. Morbi ac mauris id metus mattis aliquam et ac lacus. Praesent vel lectus a urna ornare faucibus eget eget nisl. Aliquam fermentum lorem ac magna commodo aliquet.
            </div>
        </div>

    </div>
    <div class="col-md-4">

        <div class="panel panel-default">
            <div class="panel-heading"># STEP 2</div>
            <div class="panel-body" style="text-align:right;">
                <i class="fa fa-quote-right fa-3x fa-pull-right fa-border"></i>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sodales urna tortor, in sollicitudin odio finibus et. Aenean nec nisl ultricies, condimentum tortor at, consectetur mauris. Vestibulum sit amet eros dui. Aenean maximus lacus id metus aliquam condimentum non non quam. Vivamus euismod eget nunc quis ultricies. Donec rutrum eget nisi nec sagittis. Praesent congue odio a erat consectetur, et mattis urna imperdiet. Morbi ac mauris id metus mattis aliquam et ac lacus. Praesent vel lectus a urna ornare faucibus eget eget nisl. Aliquam fermentum lorem ac magna commodo aliquet.
            </div>
        </div>

    </div>
    <div class="col-md-4">

        <div class="panel panel-default">
            <div class="panel-heading"># STEP 3</div>
            <div class="panel-body">
                <i class="fa fa-quote-left fa-3x fa-pull-left fa-border"></i>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sodales urna tortor, in sollicitudin odio finibus et. Aenean nec nisl ultricies, condimentum tortor at, consectetur mauris. Vestibulum sit amet eros dui. Aenean maximus lacus id metus aliquam condimentum non non quam. Vivamus euismod eget nunc quis ultricies. Donec rutrum eget nisi nec sagittis. Praesent congue odio a erat consectetur, et mattis urna imperdiet. Morbi ac mauris id metus mattis aliquam et ac lacus. Praesent vel lectus a urna ornare faucibus eget eget nisl. Aliquam fermentum lorem ac magna commodo aliquet.
            </div>
        </div>

    </div>

</div>
