<?php
$translate = Yaf\Registry::get("translate");
$session = SessionModel::getInstance();
?>
<!DOCTYPE html>
<!--[if IE 8]>
<html class="ie8 no-js" lang="en"><![endif]-->
<!--[if IE 9]>
<html class="ie9 no-js" lang="en"><![endif]-->
<!--[if !IE]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->
<!-- start: HEAD -->
<head>
    <title><?= $this->layout['meta_title'] ?></title>
    <!-- start: META -->
    <meta charset="utf-8"/>
    <!--[if IE]>
    <meta http-equiv='X-UA-Compatible' content="IE=edge,IE=9,IE=8,chrome=1"/><![endif]-->
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta content="" name="description"/>
    <meta content="" name="author"/>
    <!-- end: META -->
    <!-- start: MAIN CSS -->
    <link rel="stylesheet" href="/backend/assets/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/backend/assets/plugins/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="/backend/assets/fonts/style.css">
    <link rel="stylesheet" href="/backend/assets/css/main.css">
    <link rel="stylesheet" href="/backend/assets/css/main-responsive.css">
    <link rel="stylesheet" href="/backend/assets/plugins/iCheck/skins/all.css">
    <link rel="stylesheet" href="/backend/assets/plugins/bootstrap-colorpalette/css/bootstrap-colorpalette.css">
    <link rel="stylesheet" href="/backend/assets/plugins/perfect-scrollbar/src/perfect-scrollbar.css">
    <!--<link rel="stylesheet" href="/backend/assets/css/theme_light.css" type="text/css" id="skin_color">-->
    <link rel="stylesheet" href="/backend/assets/css/print.css" type="text/css" media="print"/>
    <!--[if IE 7]>
    <link rel="stylesheet" href="/backend/assets/plugins/font-awesome/css/font-awesome-ie7.min.css">
    <![endif]-->
    <!-- end: MAIN CSS -->
    <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
    <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
</head>
<!-- end: HEAD -->
<!-- start: BODY -->
<body class="login example2">
<div class="main-login col-sm-4 col-sm-offset-4">
    <div class="logo"><img src="/backend/assets/images/myseat.png" alt="MySeat"></div>
    <!-- start: LOGIN BOX -->
    <div class="box-login">
        <h3><?= $translate->_("Sign in to your account") ?></h3>

        <p>
            <?php
            if (strlen(Yaf\Registry::get("Error")) > 0) {
                echo '<div class="alert alert-danger"><span class="label label-danger">' . $translate->_("Error.") . '</span> <span> ' . Yaf\Registry::get("Error") . '</span></div>';
            } else {
                echo $translate->_("Please enter your name and password to log in.");
            }
            ?>
        </p>

        <form class="form-login" action="/" METHOD="POST">
            <div class="errorHandler alert alert-danger no-display">
                <i class="fa fa-remove-sign"></i> <?= $translate->_("You have some form errors. Please check below."); ?>
            </div>
            <fieldset>
                <div class="form-group">
                            <span class="input-icon">
                                <input type="text" class="form-control" name="username" placeholder="Username">
                                <i class="fa fa-user"></i> </span>
                </div>
                <div class="form-group form-actions">
                            <span class="input-icon">
                                <input type="password" class="form-control password" name="password"
                                       placeholder="Password">
                                <i class="fa fa-lock"></i>
                                <a class="forgot" href="#">
                                    <?php echo $translate->_("I forgot my password");?>
                                </a>
                            </span>
                </div>
                <div class="form-actions">
                    <label for="remember" class="checkbox-inline">
                        <input type="checkbox" class="grey remember" id="remember" name="remember">
                        <?= $translate->_("Keep me signed in") ?>
                    </label>
                    <button type="submit" class="btn btn-bricky pull-right">
                        <?= $translate->_("Login") ?> <i class="fa fa-arrow-circle-right"></i>
                    </button>
                </div>
            </fieldset>
        </form>
    </div>
    <!-- end: LOGIN BOX -->
    <!-- start: FORGOT BOX -->
    <div class="box-forgot" id="box-forgot">
        <h3><?= $translate->_("Forget Password?") ?></h3>

        <p>
            <?= $translate->_("Enter your e-mail address below to reset your password.") ?>
        </p>
        <div id="error_div"></div>

        <form class="form-forgot">
            <div class="errorHandler alert alert-danger no-display">
                <i class="fa fa-remove-sign"></i> <?= $translate->_("You have some form errors. Please check below.") ?>
            </div>
            <fieldset>
                <div class="form-group">
                            <span class="input-icon">
                                <input type="email" class="form-control" name="email" placeholder="Email" id="email_f">
                                <i class="fa fa-envelope"></i> </span>
                </div>
                <div class="form-actions">
                    <a class="btn btn-light-grey go-back">
                        <i class="fa fa-circle-arrow-left"></i> <?= $translate->_("Back") ?>
                    </a>
                    <button type="button" class="btn btn-bricky pull-right" onclick="ForgotPassword();">
                        <?= $translate->_("Submit") ?> <i class="fa fa-arrow-circle-right"></i>
                    </button>
                </div>
            </fieldset>
        </form>
    </div>
    <!-- end: FORGOT BOX -->

    <!-- start: COPYRIGHT -->
    <div class="copyright">
        2014 &copy; <a href="<?= $translate->_("http://www.myseat.fr/") ?>" target="_BLANK">MySeat</a>.
    </div>
    <!-- end: COPYRIGHT -->
</div>
<!-- start: MAIN JAVASCRIPTS -->
<!--[if lt IE 9]>
<script src="/backend/assets/plugins/respond.min.js"></script>
<script src="/backend/assets/plugins/excanvas.min.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<![endif]-->
<!--[if gte IE 9]><!-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<!--<![endif]-->
<script src="/backend/assets/plugins/jquery-ui/jquery-ui-1.10.2.custom.min.js"></script>
<script src="/backend/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/backend/assets/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js"></script>
<script src="/backend/assets/plugins/blockUI/jquery.blockUI.js"></script>
<script src="/backend/assets/plugins/iCheck/jquery.icheck.min.js"></script>
<script src="/backend/assets/plugins/perfect-scrollbar/src/jquery.mousewheel.js"></script>
<script src="/backend/assets/plugins/perfect-scrollbar/src/perfect-scrollbar.js"></script>
<script src="/backend/assets/plugins/less/less-1.5.0.min.js"></script>
<script src="/backend/assets/plugins/jquery-cookie/jquery.cookie.js"></script>
<script src="/backend/assets/plugins/bootstrap-colorpalette/js/bootstrap-colorpalette.js"></script>
<script src="/backend/assets/js/main.js"></script>
<!-- end: MAIN JAVASCRIPTS -->
<!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
<script src="/backend/assets/plugins/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="/backend/assets/js/login.js"></script>
<!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
<script>
    jQuery(document).ready(function () {
        Main.init();
        Login.init();
    });
</script>
</body>
<!-- end: BODY -->
</html>