<?php



$translate = Yaf\Registry::get("translate");// Translation
$session = SessionModel::getInstance();// Identifie la session
//Du role de l'utilisateur de la session. Backendmenu.php
?>
<!DOCTYPE html>
<!--[if IE 8]>
<html class="ie8 no-js" lang="en"><![endif]-->
<!--[if IE 9]>  <!-- Modernizr remplace le no-js-->
<html class="ie9 no-js" lang="en"><![endif]-->
<!--[if !IE]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->
<head>
    <!-- [Bonne pratique]-->
    <meta charset="utf-8"/>
    <!-- Encodage des caractère, TT  -->
    <title><?= $this->layout['meta_title'] ?></title><!--  Supp: prend le titre d'une variable layout -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <!-- Rend la page compatible avec iphone-->
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <!-- Même-->
    <meta content="<?= $translate->_("MySeat"); ?>" name="description"/>
    <!-- Meta element utilisé pour spécifier la
        la description de page, mot clef, l'auteur, dernière modif. Donné utilisé par le navigateur -->
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
    <!-- Pour que le content soit bien display [Bonne pratique] -->
    <link rel="shortcut icon" href="/backend/assets/images/faviconmyseat22.png">
    <!-- Link definit lien entre le document et une source externe  -->
    <link rel="stylesheet" href="/backend/assets/plugins/bootstrap-switch/static/stylesheets/bootstrap-switch.css">
    <link rel="stylesheet" href="/backend/assets/plugins/bootstrap-switch/static/stylesheets/flat-ui-fonts.css">
    <link rel="stylesheet" href="/backend/assets/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/backend/assets/plugins/font-awesome/css/font-awesome.min.css">
<!--    <link rel="stylesheet" href="/frontend/assets/plugins/bootstrap-social-buttons/social-buttons.css">-->
    <link rel="stylesheet" href="/backend/assets/fonts/style.css">
    <link rel="stylesheet" href="/backend/assets/css/main.css">
    <link rel="stylesheet" href="/backend/assets/css/main-responsive.css">
    <link rel="stylesheet" href="/backend/assets/plugins/iCheck/skins/all.css">
    <link rel="stylesheet" href="/backend/assets/plugins/bootstrap-colorpalette/css/bootstrap-colorpalette.css">
    <link rel="stylesheet" href="/backend/assets/plugins/perfect-scrollbar/src/perfect-scrollbar.css">
    <link rel="stylesheet" href="/backend/assets/css/theme_<?= CUSTOMER_TEMPLATE ?>.css" type="text/css"
          id="skin_color">
    <link rel="stylesheet" href="/backend/assets/css/print.css" type="text/css" media="print"/>
    <link href="/backend/assets/plugins/bootstrap-modal/css/bootstrap-modal-bs3patch.css" rel="stylesheet"
          type="text/css"/>
    <link href="/backend/assets/plugins/bootstrap-modal/css/bootstrap-modal.css" rel="stylesheet" type="text/css"/>
    <link rel="stylesheet" href="/backend/assets/plugins/ladda-bootstrap/dist/ladda-themeless.min.css">
    <link rel="stylesheet" href="/backend/assets/plugins/pnotify/jquery.pnotify.default.css">
    <!--[if IE 7]>
    <link rel="stylesheet" href="/backend/assets/plugins/font-awesome/css/font-awesome-ie7.min.css"><![endif]-->
    <!--<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.0.2/fullcalendar.css">-->
    <?= $this->layout['css'] ?>
</head>
<body class="">

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                <span class="clip-list-2"></span>
            </button>
            <a class="navbar-brand" href="/">
                <img src="/general/assets/images/customers/avatars/<?/*= CUSTOMER_ID */?>.png" alt="<?/*= CUSTOMER_NAME */?>"
                     height="36" width="190" style="margin-top: -12px; margin-left: -20px;">
            </a>
        </div>
        <div class="navbar-tools">
            <ul class="nav navbar-right">
                <li class="dropdown current-user">
                    <a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" data-close-others="true"
                       href="#">
                        <span class="username"><?/*= $session->me['fullname'] */?></span>
                        <i class="clip-chevron-down"></i>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="/profile">
                                <i class="clip-user-2"></i>
                                &nbsp;<?/*= $translate->_("My Profile") */?>
                            </a>
                        </li>

                        <li class="divider"></li>

                        <li>
                            <a href="javascript:OpenContactForm()">
                                <i class="fa fa-envelope-o"></i>
                                &nbsp;<?/*= $translate->_("Contact Us") */?>
                            </a>
                        </li>

                        <li class="divider"></li>
                        <li>
                            <a href="/Authentification/logout">
                                <i class="clip-exit"></i>
                                <?/*= $translate->_("Log Out"); */?>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>

<div class="main-container">

    <div class="navbar-content">
        <div class="main-navigation navbar-collapse collapse ">
            <div class="navigation-toggler">
                <i class="clip-chevron-left"></i>
                <i class="clip-chevron-right"></i>
            </div>
            <ul class="main-navigation-menu">
                <?/*= $AdminmenuModel->menu_html */?>
            </ul>
        </div>
    </div>

    <div class="main-content">
        <?/*= $this->content //ici le contenu, ce qui signifie que tu charge ton code jQuery avant*/?>
    </div>
</div>

<!--        <div class="footer ">
            <div class="footer-inner">
                2014 &copy; Myseat.fr
            </div>
            <div class="footer-items">
                <span class="go-top"><i class="clip-chevron-up"></i></span>
            </div>
        </div>-->

<div id="event-management" class="modal small fade" tabindex="-1" data-width="760" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?/*= $translate->_("Event Management"); */?></h4>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn btn-light-grey">
                    Close
                </button>
                <button type="button" class="btn btn-danger remove-event no-display">
                    <i class='fa fa-trash-o'></i>
                    <?/*= $translate->_("Delete Event"); */?>
                </button>
                <button type='submit' class='btn btn-success update-event no-display'>
                    <i class='fa fa-floppy-o'></i>
                    <?/*= $translate->_("Update"); */?>
                </button>
                <button type='submit' class='btn btn-success save-event'>
                    <i class='fa fa-plus-square'></i>
                    <?/*= $translate->_("Create"); */?>
                </button>
            </div>
        </div>
    </div>
</div>
<input type="hidden" value="<?/*= time() . UUIDModel::v4() */?>" em="<?/*= $session->me['id_token'] */?>" b_id="u_<?/*= $session->me['id_hash'] */?>">
<script>
    var language = "<?= Yaf\Registry::get("language"); ?>";
</script>
<script src="/js/languages/translate.js"></script>

<!--[if lt IE 9]>
<script src="/backend/assets/plugins/respond.min.js"></script>
<script src="/backend/assets/plugins/excanvas.min.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<![endif]-->

<!--[if gte IE 9]><!-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<!--<![endif]-->

<script src="/backend/assets/plugins/jquery-ui/jquery-ui-1.10.2.custom.min.js"></script>
<script src="/backend/assets/js/jquery-ui.1.10.2.min.js"></script>
<script src="/backend/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/backend/assets/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js"></script>
<script src="/backend/assets/plugins/blockUI/jquery.blockUI.js"></script>
<script src="/backend/assets/plugins/iCheck/jquery.icheck.min.js"></script>
<script src="/backend/assets/plugins/perfect-scrollbar/src/jquery.mousewheel.js"></script>
<script src="/backend/assets/plugins/perfect-scrollbar/src/perfect-scrollbar.js"></script>
<script src="/backend/assets/plugins/less/less-1.5.0.min.js"></script>
<script src="/backend/assets/plugins/jquery-cookie/jquery.cookie.js"></script>


<!--<script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.0.2/fullcalendar.min.js"></script>-->

<script src="/backend/assets/js/main.js"></script>
<script src="/backend/assets/plugins/bootstrap-modal/js/bootstrap-modal.js"></script>
<script src="/backend/assets/plugins/bootstrap-modal/js/bootstrap-modalmanager.js"></script>
<script src="/backend/assets/plugins/ladda-bootstrap/dist/spin.min.js"></script>
<script src="/backend/assets/plugins/ladda-bootstrap/dist/ladda.min.js"></script>
<script src="/backend/assets/plugins/pnotify/jquery.pnotify.min.js"></script>
<script src="/backend/assets/js/ui-modals.js"></script>
<script src="/general/assets/js/modals.js"></script>
<script src="/general/assets/js/generale.js?=<?= time() ?>"></script>
<script src="/backend/assets/js/index.js"></script>
<?= $this->layout['scripts'] ?>
<script>$(document).ready(function () {
        Main.init();

    });</script>

<!-- End Piwik Code -->
</body>
</html>