<?php
      $session = SessionModel::getInstance();
      require_once 'backend/assets/plugins/steamauth/steamauth.php';
      include('backend/assets/plugins/steamauth/userInfo.php');
?>
<!DOCTYPE html>
<head>

    <meta charset="utf-8"/>
    <!-- Encodage des caractère, TT  -->
    <title><?= $this->layout['meta_title'] ?></title>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <!-- Rend la page compatible avec iphone-->
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <link rel="stylesheet" href="/backend/assets/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/backend/assets/css/main-new.css">
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="backend/assets/js/administration-autoform.js"></script>


</head>

<body>

<header>

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">QUI VEUT GAGNER DES SKINS ?</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class=""><a href="/Lottery"><i class="fa fa-ticket icon-navbar"></i>Lotteries</a></li>
                    <li><a href="/Returns"><i class="fa fa-gift icon-navbar"></i>Récompenses</a></li>
                    <?php

                          if (isset($session->steamid)) {

                            if($session->steam_steamid == "76561198078265100" || $session->steam_steamid == "76561198041856215")
                            {
                                ?>
                                  <li><a href="/Administration"><i class="fa fa-cog icon-navbar"></i>Administration</a></li>
                                <?php
                            }


                          }

                    ?>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                   <?php
                            if (isset($session->steamid)) {

                    ?>
                    <li>
                             <?php

                            echo "<a href=\"http://steamcommunity.com/profiles/".$session->steamid."\">";
                            echo $session->steam_personaname;
                            echo "</a>";

                             ?>


                    </li>
                    <li>
                       <?php
                            $url = $session-> steam_avatar;
                            $clean = strtok($url, '\\');
                            echo "<img src=\"".$clean."\" class=\"avatar img-circle\" />";
                       ?>
                    </li>
                    <?php
                    }

                     ?>
                    <li>

                            <?php



                            if (!isset($session->steamid)) {
                                echo steamlogin(); //login button
                            } else {



                                //Protected content
                                logoutbutton(); //Logout Button

                            }
                            ?>

                        </li>
                </ul>
            </div>
        </div>
    </nav>

</header>
<div class="main-container">
    <div class="main-content">
        <?= $this->content ?>
    </div>
</div>
<footer>

</footer>

</body>
</html>
<?php

