<?php
$session = SessionModel::getInstance();

$items = json_decode(
    file_get_contents("http://steamcommunity.com/profiles/".$session->steamid."/inventory/json/730/2")
);

?>
<legend>Ajouter une lotterie</legend>

<div class="row">


        <div class="col-md-6">

            <form method="post" class="form-horizontal">
            <fieldset>
                <div class="form-group">
                    <label for="inputID" class="col-lg-2 control-label">ID</label>

                    <div class="col-lg-10">
                        <input
                            style="background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QsPDhss3LcOZQAAAU5JREFUOMvdkzFLA0EQhd/bO7iIYmklaCUopLAQA6KNaawt9BeIgnUwLHPJRchfEBR7CyGWgiDY2SlIQBT/gDaCoGDudiy8SLwkBiwz1c7y+GZ25i0wnFEqlSZFZKGdi8iiiOR7aU32QkR2c7ncPcljAARAkgckb8IwrGf1fg/oJ8lRAHkR2VDVmOQ8AKjqY1bMHgCGYXhFchnAg6omJGcBXEZRtNoXYK2dMsaMt1qtD9/3p40x5yS9tHICYF1Vn0mOxXH8Uq/Xb389wff9PQDbQRB0t/QNOiPZ1h4B2MoO0fxnYz8dOOcOVbWhqq8kJzzPa3RAXZIkawCenHMjJN/+GiIqlcoFgKKq3pEMAMwAuCa5VK1W3SAfbAIopum+cy5KzwXn3M5AI6XVYlVt1mq1U8/zTlS1CeC9j2+6o1wuz1lrVzpWXLDWTg3pz/0CQnd2Jos49xUAAAAASUVORK5CYII=&quot;); background-repeat: no-repeat; background-attachment: scroll; background-position: right center; cursor: auto;"
                            class="form-control" name="inputID" id="inputID" placeholder="Entré un ID pour la lotterie" type="text">
                        <a id="generate-random-id" class="btn btn-info">générer</a>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputAmount" class="col-lg-2 control-label">Nombre d'entrée</label>

                    <div class="col-lg-10">
                        <input
                            style="background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QsPDhss3LcOZQAAAU5JREFUOMvdkzFLA0EQhd/bO7iIYmklaCUopLAQA6KNaawt9BeIgnUwLHPJRchfEBR7CyGWgiDY2SlIQBT/gDaCoGDudiy8SLwkBiwz1c7y+GZ25i0wnFEqlSZFZKGdi8iiiOR7aU32QkR2c7ncPcljAARAkgckb8IwrGf1fg/oJ8lRAHkR2VDVmOQ8AKjqY1bMHgCGYXhFchnAg6omJGcBXEZRtNoXYK2dMsaMt1qtD9/3p40x5yS9tHICYF1Vn0mOxXH8Uq/Xb389wff9PQDbQRB0t/QNOiPZ1h4B2MoO0fxnYz8dOOcOVbWhqq8kJzzPa3RAXZIkawCenHMjJN/+GiIqlcoFgKKq3pEMAMwAuCa5VK1W3SAfbAIopum+cy5KzwXn3M5AI6XVYlVt1mq1U8/zTlS1CeC9j2+6o1wuz1lrVzpWXLDWTg3pz/0CQnd2Jos49xUAAAAASUVORK5CYII=&quot;); background-repeat: no-repeat; background-attachment: scroll; background-position: right center; cursor: auto;"
                            class="form-control" name="inputAmount" id="inputAmount" type="number">
                    </div>
                </div>
                <div class="form-group has-warning">
                    <label for="inputDescription" class="col-lg-2 control-label">Description</label>

                    <div class="col-lg-10">
                        <input
                            style="background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QsPDhss3LcOZQAAAU5JREFUOMvdkzFLA0EQhd/bO7iIYmklaCUopLAQA6KNaawt9BeIgnUwLHPJRchfEBR7CyGWgiDY2SlIQBT/gDaCoGDudiy8SLwkBiwz1c7y+GZ25i0wnFEqlSZFZKGdi8iiiOR7aU32QkR2c7ncPcljAARAkgckb8IwrGf1fg/oJ8lRAHkR2VDVmOQ8AKjqY1bMHgCGYXhFchnAg6omJGcBXEZRtNoXYK2dMsaMt1qtD9/3p40x5yS9tHICYF1Vn0mOxXH8Uq/Xb389wff9PQDbQRB0t/QNOiPZ1h4B2MoO0fxnYz8dOOcOVbWhqq8kJzzPa3RAXZIkawCenHMjJN/+GiIqlcoFgKKq3pEMAMwAuCa5VK1W3SAfbAIopum+cy5KzwXn3M5AI6XVYlVt1mq1U8/zTlS1CeC9j2+6o1wuz1lrVzpWXLDWTg3pz/0CQnd2Jos49xUAAAAASUVORK5CYII=&quot;); background-repeat: no-repeat; background-attachment: scroll; background-position: right center; cursor: auto;"
                            class="form-control" name="inputDescription" id="inputDescription" type="text">


                    </div>
                </div>
                <div class="form-group has-warning">
                    <label for="inputState" class="col-lg-2 control-label">État</label>

                    <div class="col-lg-10">
                        <input
                            style="background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QsPDhss3LcOZQAAAU5JREFUOMvdkzFLA0EQhd/bO7iIYmklaCUopLAQA6KNaawt9BeIgnUwLHPJRchfEBR7CyGWgiDY2SlIQBT/gDaCoGDudiy8SLwkBiwz1c7y+GZ25i0wnFEqlSZFZKGdi8iiiOR7aU32QkR2c7ncPcljAARAkgckb8IwrGf1fg/oJ8lRAHkR2VDVmOQ8AKjqY1bMHgCGYXhFchnAg6omJGcBXEZRtNoXYK2dMsaMt1qtD9/3p40x5yS9tHICYF1Vn0mOxXH8Uq/Xb389wff9PQDbQRB0t/QNOiPZ1h4B2MoO0fxnYz8dOOcOVbWhqq8kJzzPa3RAXZIkawCenHMjJN/+GiIqlcoFgKKq3pEMAMwAuCa5VK1W3SAfbAIopum+cy5KzwXn3M5AI6XVYlVt1mq1U8/zTlS1CeC9j2+6o1wuz1lrVzpWXLDWTg3pz/0CQnd2Jos49xUAAAAASUVORK5CYII=&quot;); background-repeat: no-repeat; background-attachment: scroll; background-position: right center; cursor: auto;"
                            class="form-control" name="inputState" id="inputState" type="text">


                    </div>
                </div>
                <div class="form-group has-error">
                    <label for="inputState" class="col-lg-2 control-label">ClassID</label>

                    <div class="col-lg-10">
                        <input
                            style="background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QsPDhss3LcOZQAAAU5JREFUOMvdkzFLA0EQhd/bO7iIYmklaCUopLAQA6KNaawt9BeIgnUwLHPJRchfEBR7CyGWgiDY2SlIQBT/gDaCoGDudiy8SLwkBiwz1c7y+GZ25i0wnFEqlSZFZKGdi8iiiOR7aU32QkR2c7ncPcljAARAkgckb8IwrGf1fg/oJ8lRAHkR2VDVmOQ8AKjqY1bMHgCGYXhFchnAg6omJGcBXEZRtNoXYK2dMsaMt1qtD9/3p40x5yS9tHICYF1Vn0mOxXH8Uq/Xb389wff9PQDbQRB0t/QNOiPZ1h4B2MoO0fxnYz8dOOcOVbWhqq8kJzzPa3RAXZIkawCenHMjJN/+GiIqlcoFgKKq3pEMAMwAuCa5VK1W3SAfbAIopum+cy5KzwXn3M5AI6XVYlVt1mq1U8/zTlS1CeC9j2+6o1wuz1lrVzpWXLDWTg3pz/0CQnd2Jos49xUAAAAASUVORK5CYII=&quot;); background-repeat: no-repeat; background-attachment: scroll; background-position: right center; cursor: auto;"
                            class="form-control" disabled="" name="inputClassID" id="inputClassID" type="text">


                    </div>
                </div>
                <div class="form-group has-error">
                    <label for="inputState" class="col-lg-2 control-label">ImageUrl</label>

                    <div class="col-lg-10">
                        <input
                            style="background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QsPDhss3LcOZQAAAU5JREFUOMvdkzFLA0EQhd/bO7iIYmklaCUopLAQA6KNaawt9BeIgnUwLHPJRchfEBR7CyGWgiDY2SlIQBT/gDaCoGDudiy8SLwkBiwz1c7y+GZ25i0wnFEqlSZFZKGdi8iiiOR7aU32QkR2c7ncPcljAARAkgckb8IwrGf1fg/oJ8lRAHkR2VDVmOQ8AKjqY1bMHgCGYXhFchnAg6omJGcBXEZRtNoXYK2dMsaMt1qtD9/3p40x5yS9tHICYF1Vn0mOxXH8Uq/Xb389wff9PQDbQRB0t/QNOiPZ1h4B2MoO0fxnYz8dOOcOVbWhqq8kJzzPa3RAXZIkawCenHMjJN/+GiIqlcoFgKKq3pEMAMwAuCa5VK1W3SAfbAIopum+cy5KzwXn3M5AI6XVYlVt1mq1U8/zTlS1CeC9j2+6o1wuz1lrVzpWXLDWTg3pz/0CQnd2Jos49xUAAAAASUVORK5CYII=&quot;); background-repeat: no-repeat; background-attachment: scroll; background-position: right center; cursor: auto;"
                            class="form-control" name="inputImageUrl" id="inputImageUrl" type="text">


                    </div>
                </div>
                <div class="form-group has-warning">
                    <label for="inputPrice" class="col-lg-2 control-label">Prix</label>

                    <div class="col-lg-10">
                        <div class="input-group">
                            <span class="input-group-addon">$</span>
                            <input name="inputPrice" id="inputPrice" class="form-control" type="text">
                        </div>
                        <span class="help-block">Ne pas remplir les champs en orange et rouge !</span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-lg-10 col-lg-offset-2">
                        <button type="reset" class="btn btn-default">Annuler</button>
                        <button type="submit" name="submit" class="btn btn-primary">Valider</button>
                    </div>
                </div>
            </fieldset>
        </form>
        </div>
        <div class="col-md-6">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">Inventaire Steam</h3>
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <label for="select" class="col-lg-2 control-label">Skin de l'arme</label>

                        <div class="col-lg-10">
                            <select class="form-control" id="select">
                                <?php
                                foreach ($items->rgDescriptions as $key => $val) {


                                    $elements = array("currency" => 3, "appid" => 730, "market_hash_name" => $val->market_hash_name);
                                    $file = StaticModel::GetUrlContent("http://steamcommunity.com/market/priceoverview/", $elements);
                                    $items_price = json_decode($file);


                                    echo "<option>".$val->market_hash_name." | ".$items_price->lowest_price." | ".$val->icon_url."</option>";


                                }
                                ?>
                            </select>

                        </div>
                    </div>
                </div>
            </div>
        </div>


</div>
<legend>Supprimer une lotterie</legend>

<div class="row">

    <div class="col-md-12">
        <form method="post" class="form-horizontal">
            <fieldset>
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3 class="panel-title">Liste des lotteries</h3>
                    </div>
                    <div class="panel-body">
                        <div class="form-group">
                            <label for="select" class="col-lg-2 control-label">Choisir la lotterie à supprimer</label>

                            <div class="col-lg-10">
                                <select class="form-control" id="selectLotterie">
                                    <?php

                                        foreach ($this->$GLOBAL as $value) {
                                            foreach ($value as $key => $lotteryb) {
                                                foreach ($lotteryb as $key => $lottery) {
                                                    if(!empty($lottery->sub_id))
                                                    {
                                                        if ($lottery->lottery_ended == 1 ) {
                                                            echo "<option>#".$lottery->sub_id." ( ".$lottery->item_description." )[TERMINÉE] </option>";

                                                        } else {
                                                            echo "<option>#".$lottery->sub_id." ( ".$lottery->item_description." )[EN COURS] </option>";

                                                        }
                                                    }

                                                }

                                            }
                                        }
                                    ?>
                                </select>

                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-10">
                        <input type="text" nclass="form-control" name="inputLotterie" id="inputLotterie" value="<?php echo $lottery->sub_id ?>" style="display:none;"/>

                        <button type="submit" name="submit" class="btn btn-primary">Valider</button>
                    </div>
                </div>
            <fieldset>
        </form>
    </div>

</div>
<legend>Rapport des réclamations</legend>

<div class="row">

    <div class="col-md-12">
            <fieldset>
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3 class="panel-title">Liste des réclamations</h3>
                    </div>
                    <div class="panel-body">
                        <div class="form-group">
                            <?php

                            foreach ($this->$GLOBAL as $key => $value) {
                                foreach ($value as $key => $claims) {

                                    foreach ($claims as $key => $claims_t) {
                                        if (!empty($claims_t->idLotterie)) {
                                            if ($claims_t->validate == 0) {
                                                ?>
                                                <div class="alert alert-dismissible alert-danger">
                                                    <strong>RAPPEL!</strong> Vous n'avez pas récompensé <?php echo "<a href=\"http://steamcommunity.com/profiles/\".'$claims_t->idSteam'."; ?>
                                                                                                           class="alert-link"><?php echo $claims_t->hashname_steam ?></a>
                                                    pour la lotterie <a href="/Returns"
                                                                        class="alert-link">#<?php echo $claims_t->idLotterie ?></a>.

                                                    <form method="post" class="form-horizontal">
                                                        <div class="form-group">
                                                            <div class="col-lg-10">
                                                                <button type="submit" name="submit" class="btn btn-success"><i class="fa fa-thumbs-o-up"></i></button>
                                                                <input type="text" nclass="form-control" name="idlotterie" id="idlotterie" value="<?php echo $claims_t->idLotterie ?>" style="display:none;"/>

                                                                <a href="#" class="btn btn-warning">Consulter profile</a>
                                                            </div>
                                                        </div>


                                                    </form>

                                                </div>
                                                <?php
                                            } else {
                                                ?>
                                                <div class="alert alert-dismissible alert-success">
                                                    <strong>OK!</strong> Vous avez déjà récompensé <a href="#"
                                                                                                      class="alert-link"><?php echo $claims_t->hashname_steam ?></a> pour la lotterie <a href="/Returns"
                                                                                                        class="alert-link">#<?php echo $claims_t->idLotterie ?></a>

                                                    .
                                                </div>
                                                <?php

                                            }
                                        }
                                    }
                                }
                            }


                            ?>

                        </div>
                    </div>
                </div>

            <fieldset>

    </div>

</div>