<?php
$translate = Yaf\Registry::get("translate");
?>

<section class="page-top">
    <div class="container">
        <div class="col-md-4 col-sm-4">
            <h1><?= $translate->_("Login"); ?></h1>
        </div>
        <div class="col-md-8 col-sm-8">
            <ul class="pull-right breadcrumb">
                <li>
                    <a href="/">
                        <?= $translate->_("Home"); ?>
                    </a>
                </li>
                <li class="active">
                    <?= $translate->_("Login"); ?>
                </li>
            </ul>
        </div>
    </div>
</section>

<section class="wrapper">
    <div class="container">
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="clip-user"></i>
                    <?= $translate->_("Login"); ?>
                </div>
                <div class="panel-body">
                    <?php if (isset($this->error) && $this->error !== "") { ?>
                        <div class="alert alert-danger" style="margin-bottom:0px;">
                            <button data-dismiss="alert" class="close">×</button>
                            <i class="fa fa-exclamation-triangle"></i>
                            <?= $this->error ?>
                        </div>
                        <hr style="margin:4px auto">
                    <?php } ?>
                    <form class="form-horizontal" role="form" id="loginForm" method="post" action="/Authentification">
                        <div class="form-group">
                            <label for="inputUsername" class="col-sm-2 control-label">
                                <?= $translate->_("Email"); ?>
                            </label>

                            <div class="col-sm-9">
                                <input type="text" id="inputUsername" class="form-control input-sm" name="username"
                                       placeholder="<?= $translate->_("Email"); ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword" class="col-sm-2 control-label">
                                <?= $translate->_("Password"); ?>
                            </label>

                            <div class="col-sm-9">
                                <input type="password" id="inputPassword" class="form-control input-sm" name="password"
                                       placeholder="Password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="text-center">
                                <a class="btn btn-success btn-squared btn-lg" onclick="send_login_form();" href='#'>Login</a>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="text-center">
                                <a class="btn btn-danger btn-squared btn-xs"
                                   href="/forgotpassword"><?= $translate->_("Forgot Your Password ?"); ?></a>
                                <a class="btn btn-warning btn-squared btn-xs"
                                   href="/resendactivation"><?= $translate->_("Resend Your Activation Code ?"); ?></a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>