<?php
$session = SessionModel::getInstance();
require_once 'backend/assets/plugins/steamauth/steamauth.php';
include('backend/assets/plugins/steamauth/userInfo.php');
?>


    <?php
    foreach ($this->$results as $key => $value){
    foreach ($value as $key => $lottery){
    ?>
    <div class="col-md-2 colonne">

    <div class="card text-xs-center">
        <div class="card-header">
          <span class="list-lotterie">Lotterie #</span><?php echo $lottery->sub_id ?>

        </div>


        <div class="card-block">
            <?php echo "<img class='weapon_img' src='http://steamcommunity-a.akamaihd.net/economy/image/".$lottery->imageurl."'";?>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <span class="list-lotterie">Participants :</span>
                    <?php
                    if(sizeof($lottery->test) == 0)
                    {
                        echo '0 sur '.$lottery->entry;
                    }
                    else
                    {


                        foreach ($lottery->test as $key => $value) {

                            echo $value->Total.' sur '.$lottery->entry;



                        }
                    }
                    ?>


                </li>
                <li class="list-group-item"><span class="list-lotterie">Skin :</span> <?php echo $lottery->item_description ?></li>
                <li class="list-group-item"><span class="list-lotterie">État :</span> <?php echo $lottery->item_state ?></li>
                <li class="list-group-item"><span class="list-lotterie">Valeur :</span> <?php echo $lottery->item_value ?></li>
            </ul>
            <?php
            if (isset($session->steamid)) {
                ?>

                    <form class="form-horizontal" method="post">
                        <input type="text" nclass="form-control" name="lotteryID" id="lotteryID" value="<?php echo $lottery->sub_id ?>" style="display:none;"/>
                        <button type="submit" class="btn btn-primary" style="margin-top:10px;">Participer</button>
                    </form>

                <?php

            }
            ?>
        </div>
        <div class="card-footer text-muted">
            <?php

            $var =  StaticModel::time_elapsed_string($lottery->starting_date);
            echo $var;

            ?>
        </div>
    </div>

    </div>
    <?php
        }
    }
    ?>

